/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BScroll: typeof import('./src/components/b-scroll/b-scroll.vue')['default']
    DataTime: typeof import('./src/components/data-time/data-time.vue')['default']
    FullLoadingCpn: typeof import('./src/components/full-loading/full-loading-cpn.vue')['default']
    IconSelect: typeof import('./src/components/Icon/IconSelect/IconSelect.vue')['default']
    NavBar: typeof import('./src/components/nav-bar/nav-bar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollWrap: typeof import('./src/components/scroll-wrap/scroll-wrap.vue')['default']
    SvgIcon: typeof import('./src/components/Icon/SvgIcon/SvgIcon.vue')['default']
    TabBar: typeof import('./src/components/tab-bar/tab-bar.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanImagePreview: typeof import('vant/es')['ImagePreview']
    VanLoading: typeof import('vant/es')['Loading']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanRate: typeof import('vant/es')['Rate']
    VanSearch: typeof import('vant/es')['Search']
    VanSlider: typeof import('vant/es')['Slider']
    VanSpace: typeof import('vant/es')['Space']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
  }
}
